- id: '1704620538731'
  alias: Home Assistant Auto-update on a schedule base
  description: ''
  use_blueprint:
    path: edwardtfn/auto_update_scheduled.yaml
    input:
      schedule_entity: schedule.homeassistant_updates
      backup_bool: false
      restart_bool: true
      actions_pre_restart:
      - service: hassio.addon_restart
        metadata: {}
        data:
          addon: a0d7b954_ssh
      actions_pre_update:
      - service: notify.telegram_fabian
        metadata: {}
        data:
          title: Homeassistant Updates werden installiert
          message: '{{ updates_list }}'
- id: '1704620672780'
  alias: Home Assistant Auto-update on a schedule base
  description: ''
  use_blueprint:
    path: edwardtfn/auto_update_scheduled.yaml
    input:
      schedule_entity: schedule.homeassistant_updates
      restart_bool: true
      actions_pre_update:
      - service: notify.telegram_fabian
        metadata: {}
        data:
          title: Homeassistant Updates werden installiert
          message: '{{ updates_list }}'
      actions_pre_restart:
      - service: hassio.addon_restart
        metadata: {}
        data:
          addon: a0d7b954_ssh
- id: '1704620740472'
  alias: Install HA Updates automatically
  description: ''
  use_blueprint:
    path: edwardtfn/auto_update_scheduled.yaml
    input:
      schedule_entity: schedule.homeassistant_updates
      restart_bool: true
      actions_pre_restart:
      - service: hassio.addon_restart
        metadata: {}
        data:
          addon: a0d7b954_ssh
      actions_pre_update:
      - service: notify.telegram_fabian
        metadata: {}
        data:
          title: Homeassistant Updates werden installiert
          message: '{{ updates_list }}'
