animated_background:
  default_url: "https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4"
  entity: weather.dwd_weather_ebersberg_halbing
  state_url:
    clear-night:
      - "https://cdn.flixel.com/flixel/x9dr8caygivq5secll7i.hd.mp4"
      - "https://cdn.flixel.com/flixel/v26zyfd6yf0r33s46vpe.hd.mp4"
      - "https://cdn.flixel.com/flixel/ypy8bw9fgw1zv2b4htp2.hd.mp4"
      - "https://cdn.flixel.com/flixel/rosz2gi676xhkiw1ut6i.hd.mp4"
    cloudy:
      - "https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4"
      - "https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4"
      - "https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4"
      - "https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4"
      - "https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4"
      - "https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4"
    fog:
      - "https://cdn.flixel.com/flixel/vwqzlk4turo2449be9uf.hd.mp4"
      - "https://cdn.flixel.com/flixel/5363uhabodwwrzgnq6vx.hd.mp4"
    mostlycloudy:
      - "https://cdn.flixel.com/flixel/e95h5cqyvhnrk4ytqt4q.hd.mp4"
      - "https://cdn.flixel.com/flixel/l2bjw34wnusyf5q2qq3p.hd.mp4"
      - "https://cdn.flixel.com/flixel/rrgta099ulami3zb9fd2.hd.mp4"
    partlycloudy:
      - "https://cdn.flixel.com/flixel/13e0s6coh6ayapvdyqnv.hd.mp4"
      - "https://cdn.flixel.com/flixel/aorl3skmssy7udwopk22.hd.mp4"
      - "https://cdn.flixel.com/flixel/qed6wvf2igukiioykg3r.hd.mp4"
      - "https://cdn.flixel.com/flixel/3rd72eezaj6d23ahlo7y.hd.mp4"
      - "https://cdn.flixel.com/flixel/9m11gd43m6qn3y93ntzp.hd.mp4"
      - "https://cdn.flixel.com/flixel/hrkw2m8eofib9sk7t1v2.hd.mp4"
    rainy: "https://cdn.flixel.com/flixel/f0w23bd0enxur5ff0bxz.hd.mp4"
    sunny:
      - "https://cdn.flixel.com/flixel/hlhff0h8md4ev0kju5be.hd.mp4"
      - "https://cdn.flixel.com/flixel/zjqsoc6ecqhntpl5vacs.hd.mp4"
      - "https://cdn.flixel.com/flixel/jvw1avupguhfbo11betq.hd.mp4"
      - "https://cdn.flixel.com/flixel/8cmeusxf3pkanai43djs.hd.mp4"
      - "https://cdn.flixel.com/flixel/guwb10mfddctfvwioaex.hd.mp4"
path: default_view
title: Fabian's Smart Home
views:
  - badges:
      - entity: person.fabian
      - entity: person.nessie
      - entity: sensor.fabianphone_battery_level
      - entity: sensor.nessiephone_battery_level
      - entity: sensor.ipad_battery_level
      - entity: sensor.fs_smspin
      - entity: sensor.washing_machine_state
      - entity: sensor.nessie_pc_energy_today
      - entity: sensor.nessie_pc_energy_power
      - entity: sensor.fabian_strom_energy_today
      - entity: sensor.fabian_strom_energy_power
      - entity: sensor.waschmaschine_energy_power
      - entity: sensor.zorneding_to_leuchtenbergring
    cards:
      - entities:
          - entity: switch.lichtschalter
          - entity: switch.deckenlampe
          - entity: light.bett_gluhbirne
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - entity: light.lampe_gastezimmer
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - entity: light.leds_wohnzimmer
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - entity: light.leds_tisch
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - entity: light.leds_gastezimmer
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - entity: light.yeelight_strip1_34ce008b1863
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - entity: light.yeelight_color1_34ce008bcc9d
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - entity: light.keller_gluhbirne
            group: true
            toggle: true
            type: "custom:slider-entity-row"
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - entity: switch.waschmaschine
          - entity: switch.bett
          - entity: switch.fabian_strom
          - entity: switch.schreibtisch
          - entity: switch.nessie_pc
          - entity: switch.fernseher
          - entity: switch.staubsauger
          - entity: input_boolean.kuehlschrank_keller
          - entity: input_boolean.strom_keller
          - entity: input_boolean.steckerleiste_keller
          - entity: switch.schloss
        show_header_toggle: true
        title: Strom
        type: entities
      - entities:
          - switch.nessie_pc_shutdown
          - switch.fabian_pc_shutdown
          - input_boolean.silent_mode
        show_header_toggle: true
        title: PC & mehr
        type: entities
      - entity: climate.wohnzimmer
        type: "custom:simple-thermostat"
        sensors:
          - entity: sensor.wohnzimmer_humidity
      - entity: climate.schlafzimmer
        type: "custom:simple-thermostat"
        sensors:
          - entity: sensor.schlafzimmer_humidity
      - entity: climate.gastezimmer
        type: "custom:simple-thermostat"
        sensors:
          - entity: sensor.gastezimmer_humidity
      - entity: climate.bad
        type: "custom:simple-thermostat"
        sensors:
          - entity: sensor.bad_humidity
      - artwork: cover
        entity: media_player.wohnzimmer_tv
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.wohnzimmer_tv_cast
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.wohnzimmer_mini
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.schlafzimmer
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.keller_tv
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.keller_tv_cast
        type: "custom:mini-media-player"
      - type: glance
        entities:
          - entity: sensor.wohnzimmer_humidity
          - entity: sensor.schlafzimmer_humidity
          - entity: sensor.gastezimmer_humidity
          - entity: sensor.bad_humidity
        title: Luftfeuchtigkeit
      - entity: weather.dwd_weather_ebersberg_halbing
        number_of_forecasts: "5"
        type: "custom:weather-card"
      - artwork: cover
        entity: media_player.gastezimmer_mini
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.mini_gruppe
        type: "custom:mini-media-player"
    icon: "mdi:home-variant"
    title: Home
  - icon: "mdi:bed-empty"
    path: schlafzimmer
    title: Schlafzimmer
    badges: []
    cards:
      - entities:
          - entity: switch.lichtschalter
          - entity: light.yeelight_strip1_34ce008b1863
          - entity: light.bett_gluhbirne
          - entity: light.leds_tisch
          - entity: switch.bett
        show_header_toggle: true
        title: Licht & Strom
        type: entities
      - entities:
          - entity: switch.schreibtisch
          - entity: switch.fabian_strom
          - entity: device_tracker.fabianpc
          - entity: device_tracker.fabian_dock
          - entity: switch.fabian_pc_shutdown
          - entity: sensor.fabian_strom_energy_today
          - entity: sensor.fabian_strom_energy_power
        show_header_toggle: true
        title: Fabian PC
        type: entities
      - entity: climate.schlafzimmer
        type: "custom:simple-thermostat"
        sensors:
          - entity: sensor.schlafzimmer_humidity
      - artwork: cover
        entity: media_player.schlafzimmer
        type: "custom:mini-media-player"
  - badges: []
    cards:
      - entities:
          - entity: light.leds_wohnzimmer
            group: true
            toggle: true
            type: "custom:slider-entity-row"
          - switch.deckenlampe
          - entity: light.yeelight_color1_34ce008bcc9d
            group: true
            toggle: true
            type: "custom:slider-entity-row"
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - entity: switch.fernseher
          - entity: switch.staubsauger
        show_header_toggle: true
        title: Strom
        type: entities
      - entity: climate.wohnzimmer
        type: "custom:simple-thermostat"
        sensors:
          - entity: sensor.wohnzimmer_humidity
      - artwork: cover
        entity: media_player.wohnzimmer_tv
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.wohnzimmer_tv_cast
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.wohnzimmer_mini
        type: "custom:mini-media-player"
    icon: "mdi:television"
    path: wohnzimmer
    title: Wohnzimmer
  - badges: []
    cards:
      - entities:
          - light.lampe_gastezimmer
          - light.leds_gastezimmer
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - entity: switch.nessie_pc
          - entity: switch.nessie_pc_shutdown
          - entity: device_tracker.nessiepc
          - entity: sensor.nessie_pc_energy_power
          - entity: sensor.nessie_pc_energy_today
        show_header_toggle: false
        title: Nessie PC
        type: entities
      - entity: climate.gastezimmer
        type: "custom:simple-thermostat"
        sensors:
          - entity: sensor.gastezimmer_humidity
      - artwork: cover
        entity: media_player.gastezimmer_mini
        type: "custom:mini-media-player"
    icon: "mdi:desktop-tower"
    path: gastezimmer
    title: Gästezimmer
  - badges: []
    cards:
      - entities:
          - entity: light.keller_gluhbirne
            group: true
            toggle: true
            type: "custom:slider-entity-row"
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - entity: input_boolean.kuehlschrank_keller
          - entity: input_boolean.strom_keller
          - entity: input_boolean.steckerleiste_keller
        show_header_toggle: true
        title: Mehrfachsteckdose
        type: entities
      - entities:
          - entity: switch.waschmaschine
          - entity: sensor.waschmaschine_energy_power
          - entity: sensor.washing_machine_state
          - entity: sensor.washing_machine_mode
          - entity: sensor.washing_machine_finish_time
          - entity: sensor.washing_machine_finish_duration
        show_header_toggle: false
        title: Waschmaschine
        type: entities
      - artwork: cover
        entity: media_player.keller_tv
        type: "custom:mini-media-player"
      - artwork: cover
        entity: media_player.keller_tv_cast
        type: "custom:mini-media-player"
    icon: "mdi:washing-machine"
    path: keller
    title: Keller
  - badges: []
    cards:
      - buttons:
          back:
            call: androidtv.adb_command
            data:
              command: input keyevent 4
              entity_id: media_player.wohnzimmer_tv
          bottom:
            call: androidtv.adb_command
            data:
              command: input keyevent 20
              entity_id: media_player.wohnzimmer_tv
          clickleft:
            call: androidtv.adb_command
            data:
              command: input keyevent 21
              entity_id: media_player.wohnzimmer_tv
          clickright:
            call: androidtv.adb_command
            data:
              command: input keyevent 22
              entity_id: media_player.wohnzimmer_tv
          home:
            call: androidtv.adb_command
            data:
              command: input keyevent 3
              entity_id: media_player.wohnzimmer_tv
          ok:
            call: androidtv.adb_command
            data:
              command: input keyevent 66
              entity_id: media_player.wohnzimmer_tv
          power:
            call: androidtv.adb_command
            data:
              command: input keyevent 26
              entity_id: media_player.wohnzimmer_tv
          top:
            call: androidtv.adb_command
            data:
              command: input keyevent 19
              entity_id: media_player.wohnzimmer_tv
          volumedown:
            call: androidtv.adb_command
            data:
              command: input keyevent 25
              entity_id: media_player.wohnzimmer_tv
          volumeup:
            call: androidtv.adb_command
            data:
              command: input keyevent 24
              entity_id: media_player.wohnzimmer_tv
        name: Wohnzimmer TV
        remote_template: mibox
        type: "custom:generic-remote-control-card"
      - buttons:
          back:
            call: androidtv.adb_command
            data:
              command: input keyevent 4
              entity_id: media_player.keller_tv
          bottom:
            call: androidtv.adb_command
            data:
              command: input keyevent 20
              entity_id: media_player.keller_tv
          clickleft:
            call: androidtv.adb_command
            data:
              command: input keyevent 21
              entity_id: media_player.keller_tv
          clickright:
            call: androidtv.adb_command
            data:
              command: input keyevent 22
              entity_id: media_player.keller_tv
          home:
            call: androidtv.adb_command
            data:
              command: input keyevent 3
              entity_id: media_player.keller_tv
          ok:
            call: androidtv.adb_command
            data:
              command: input keyevent 66
              entity_id: media_player.keller_tv
          power:
            call: androidtv.adb_command
            data:
              command: input keyevent 26
              entity_id: media_player.keller_tv
          top:
            call: androidtv.adb_command
            data:
              command: input keyevent 19
              entity_id: media_player.keller_tv
          volumedown:
            call: androidtv.adb_command
            data:
              command: input keyevent 25
              entity_id: media_player.keller_tv
          volumeup:
            call: androidtv.adb_command
            data:
              command: input keyevent 24
              entity_id: media_player.keller_tv
        name: Keller TV
        remote_template: mibox
        type: "custom:generic-remote-control-card"
    icon: "mdi:remote-tv"
    panel: true
    path: remote
    title: remote
  - path: router
    title: Frtizbox
    icon: "mdi:router-wireless"
    visible:
      - user: b3f36b2d84254a458f3e592a2eb7b130
      - user: 427eee202b4c4ffbad381db4991972dc
    badges: []
    cards:
      - entity: switch.adguard_protection
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: button
      - entity: switch.adguard_filtering
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: button
      - entity: sensor.adguard_dns_queries
        max: 100
        min: 0
        type: gauge
      - entities:
          - entity: switch.fritzbox_7590_wifi
          - entity: switch.fritzbox_7590_wifi_5ghz
          - entity: switch.fritzbox_7590_guest_wifi
        title: FritzBox WLAN Verwaltung
        type: entities
        show_header_toggle: false
        state_color: true
      - entities:
          - entity: switch.fritzbox_7590_portforward_http_server
          - entity: switch.fritzbox_7590_portforward_https_server
          - entity: switch.fritzbox_7590_portforward_ssh
          - entity: switch.fritzbox_7590_portforward_bitwarden
          - entity: switch.fritzbox_7590_portforward_nginx_proxy
        title: FritzBox Portforwarding
        type: entities
        show_header_toggle: false
        state_color: false
  - title: RaspberryPi
    path: raspberrypi
    icon: "mdi:raspberry-pi"
    badges: []
    cards:
      - entity: climate.rpi_cooling_fan_controller
        type: "custom:simple-thermostat"
      - type: entities
        entities:
          - entity: switch.rpi_cooling_fan
          - entity: sensor.processor_temperature
          - entity: sensor.memory_use_percent
          - entity: sensor.disk_use_percent
      - type: sensor
        entity: sensor.processor_temperature
        graph: line
        icon: "mdi:cpu-64-bit"
      - type: sensor
        entity: sensor.memory_use_percent
        graph: line
      - type: entities
        entities:
          - sensor.germany_coronavirus_deaths
          - sensor.germany_coronavirus_current
          - sensor.germany_coronavirus_confirmed
          - sensor.germany_coronavirus_recovered
        show_header_toggle: false
        title: Coronavirus Deutschland
  - title: media
    path: media
    icon: "mdi:music"
    badges: []
    cards:
      - type: "custom:spotify-card"
        limit: 10
        account: default
        spotify_entity: media_player.schlafzimmer
        playlist_type: default
        always_play_random_song: true
        default_device: media_player.schlafzimmer
        grid_covers_per_row: 5
        display_style: list
