resources:
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/simple-thermostat/simple-thermostat.js
  - type: module
    url: /local/slider-entity-row.js
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - url: /community_plugin/lovelace-animated-background/animated-background.js
    type: module
animated_background:
  default_url: /community_plugin/lovelace-animated-background/night.html
  entity: weather.wetter_darksky
  state_url:
    sunny: /community_plugin/lovelace-animated-background/sunny.html
    partlycloudy: /community_plugin/lovelace-animated-background/cloudy.html
    cloudy: /community_plugin/lovelace-animated-background/cloudy.html
    mostlycloudy: /community_plugin/lovelace-animated-background/mostlycloudy.html
    clear-night: /community_plugin/lovelace-animated-background/night.html
    fog: /community_plugin/lovelace-animated-background/fog.html
title: Fabian's Smart Home
path: default_view
views:
  - badges:
      - entity: person.fabian
      - entity: person.nessie
      - entity: sensor.fsphone_battery
      - entity: sensor.vkphone_battery
      - entity: sensor.battery_level_ipad
      - entity: sensor.fs_smspin
      - entity: sensor.washing_machine_state
      - entity: sensor.wohnzimmer_humidity
      - entity: sensor.gastezimmer_humidity
      - entity: sensor.tasmota_firmware_available
      - entity: sensor.fernseher_energy_today
      - entity: sensor.fernseher_energy_power
      - entity: sensor.fabian_strom_energy_today
      - entity: sensor.fabian_strom_energy_power
      - entity: sensor.waschmaschine_energy_power
    cards:
      - entities:
          - switch.lichtschalter
          - switch.deckenlampe
          - switch.regal_leds
          - entity: light.bett_gluhbirne
            group: true
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.lampe_gastezimmer
            group: true
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.leds_wohnzimmer
            group: true
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.leds_tisch
            group: true
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.leds_gastezimmer
            group: true
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.yeelight_strip1_34ce008b1863
            group: true
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.yeelight_color1_34ce008bcc9d
            group: true
            toggle: true
            type: 'custom:slider-entity-row'
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - switch.waschmaschine
          - switch.switch_bett
          - switch.fabian_strom
          - switch.nessie_pc
          - switch.fernseher
          - switch.ventilator
          - input_boolean.kuehlschrank_keller
          - input_boolean.strom_keller
          - input_boolean.strom2_keller
          - switch.schloss
        show_header_toggle: true
        title: Strom
        type: entities
      - entities:
          - switch.nessie_pc_shutdown
          - switch.fabian_pc_shutdown
          - input_boolean.silent_mode
        show_header_toggle: true
        title: PC & mehr
        type: entities
      - entity: climate.wohnzimmer
        sensors:
          - sensor.wohnzimmer_humidity
        type: 'custom:simple-thermostat'
      - entity: climate.schlafzimmer
        type: 'custom:simple-thermostat'
      - entity: climate.gastezimmer
        sensors:
          - sensor.gastezimmer_humidity
        type: 'custom:simple-thermostat'
      - entity: climate.bad
        type: 'custom:simple-thermostat'
      - artwork: cover
        entity: media_player.mi_box
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.mibox_s
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.wohnzimmer_mini
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.schlafzimmer
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.gastezimmer_mini
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.keller_tv
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.mini_gruppe
        type: 'custom:mini-media-player'
      - entity: weather.wetter_darksky
        type: 'custom:weather-card'
    icon: 'mdi:home-variant'
    title: Home
  - badges:
      - entity: sensor.wohnzimmer_humidity
      - entity: sensor.fernseher_energy_today
      - entity: sensor.fernseher_energy_power
    cards:
      - entities:
          - light.leds_wohnzimmer
          - switch.deckenlampe
          - light.yeelight_color1_34ce008bcc9d
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - switch.fernseher
          - switch.ventilator
        show_header_toggle: true
        title: Strom
        type: entities
      - entity: climate.wohnzimmer
        sensors:
          - sensor.wohnzimmer_humidity
        type: 'custom:simple-thermostat'
      - artwork: cover
        entity: media_player.mibox_s
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.mi_box
        type: 'custom:mini-media-player'
      - artwork: cover
        entity: media_player.wohnzimmer_mini
        type: 'custom:mini-media-player'
    icon: 'mdi:television'
    path: wohnzimmer
    title: Wohnzimmer
  - cards:
      - entities:
          - light.bett_gluhbirne
          - switch.regal_leds
          - switch.lichtschalter
          - light.leds_tisch
          - light.yeelight_strip1_34ce008b1863
          - switch.switch_bett
        show_header_toggle: true
        title: Licht & Strom
        type: entities
      - entities:
          - switch.fabian_strom
          - device_tracker.fabianpc
          - switch.fabian_pc_shutdown
          - sensor.fabian_strom_energy_today
          - sensor.fabian_strom_energy_power
        show_header_toggle: true
        title: Fabian PC
        type: entities
      - entity: climate.schlafzimmer
        type: 'custom:simple-thermostat'
      - artwork: cover
        entity: media_player.schlafzimmer
        type: 'custom:mini-media-player'
    icon: 'mdi:hotel'
    path: schlafzimmer
    title: Schlafzimmer
  - badges:
      - entity: sensor.gastezimmer_humidity
    cards:
      - entities:
          - light.lampe_gastezimmer
          - light.leds_gastezimmer
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - switch.nessie_pc
          - switch.nessie_pc_shutdown
          - device_tracker.nessiepc
        show_header_toggle: false
        title: Nessie PC
        type: entities
      - entity: climate.gastezimmer
        sensors:
          - sensor.gastezimmer_humidity
        type: 'custom:simple-thermostat'
      - artwork: cover
        entity: media_player.gastezimmer_mini
        type: 'custom:mini-media-player'
    icon: 'mdi:desktop-tower'
    path: gastezimmer
    title: Gästezimmer
  - badges:
      - entity: sensor.washing_machine_state
      - entity: sensor.waschmaschine_energy_power
    cards:
      - entities:
          - switch.waschmaschine
          - input_boolean.kuehlschrank_keller
          - input_boolean.strom_keller
          - input_boolean.strom2_keller
        show_header_toggle: true
        title: Strom
        type: entities
      - artwork: cover
        entity: media_player.keller_tv
        type: 'custom:mini-media-player'
    icon: 'mdi:washing-machine'
    path: keller
    title: Keller
