resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js 
    type: module

title: Fabian's Smart Home
path: default_view
views:
  - title: Home
    icon: mdi:home-variant
    badges:
      - entity: person.fabian
      - entity: person.nessie
      - entity: sensor.vkphone_battery
      - entity: sensor.washing_machine_state
      - entity: sensor.fs_smspin
      - entity: sensor.fsphone_battery
      - entity: sensor.battery_level_ipad
      - entity: sensor.wohnzimmer_humidity
      - entity: sensor.gastezimmer_humidity
      - entity: sensor.tasmota_firmware_available
      - entity: sensor.fernseher_energy_today
      - entity: sensor.fernseher_energy_power
      - entity: sensor.fabian_strom_energy_today
      - entity: sensor.fabian_strom_energy_power
      - entity: sensor.waschmaschine_energy_power
    cards:
      - entities:
          - light.bett_gluhbirne
          - switch.regal_leds
          - switch.lichtschalter
          - light.lampe_gastezimmer
          - light.leds_wohnzimmer
          - switch.deckenlampe
          - light.leds_tisch
          - light.leds_gastezimmer
          - light.yeelight_strip1_34ce008b1863
          - light.yeelight_color1_34ce008bcc9d
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - switch.waschmaschine
          - switch.switch_bett
          - switch.fabian_strom
          - switch.nessie_pc
          - switch.fernseher
          - switch.ventilator
          - input_boolean.kuehlschrank_keller
          - input_boolean.strom_keller
          - input_boolean.strom2_keller
          - switch.schloss
        show_header_toggle: true
        title: Strom
        type: entities
      - entities:
          - switch.nessie_pc_shutdown
          - switch.fabian_pc_shutdown
          - input_boolean.silent_mode
        show_header_toggle: true
        title: PC & mehr
        type: entities
      - entity: climate.bad
        type: thermostat
      - entity: climate.schlafzimmer
        type: thermostat
      - entity: climate.gastezimmer
        type: thermostat
      - entity: climate.wohnzimmer
        type: thermostat
      - entity: media_player.gastezimmer_mini
        type: custom:mini-media-player
      - entity: media_player.keller_tv
        type: custom:mini-media-player
      - entity: media_player.schlafzimmer
        type: custom:mini-media-player
      - entity: media_player.mi_box
        type: custom:mini-media-player
      - entity: media_player.wohnzimmer_mini
        type: custom:mini-media-player
      - entity: media_player.mini_gruppe
        type: custom:mini-media-player
      - entity: media_player.mibox_s
        type: custom:mini-media-player
      - entity: weather.wetter_darksky
        type: weather-forecast

  - title: Wohnzimmer
    path: wohnzimmer
    icon: mdi:television
    badges:
      - entity: sensor.wohnzimmer_humidity
      - entity: sensor.fernseher_energy_today
      - entity: sensor.fernseher_energy_power
    cards:
      - entities:
          - light.leds_wohnzimmer
          - switch.deckenlampe
          - light.yeelight_color1_34ce008bcc9d
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - switch.fernseher
          - switch.ventilator
        show_header_toggle: true
        title: Strom
        type: entities
      - entity: climate.wohnzimmer
        type: thermostat
      - entity: media_player.mibox_s
        type: custom:mini-media-player
      - entity: media_player.mi_box
        type: custom:mini-media-player
      - entity: media_player.wohnzimmer_mini
        type: custom:mini-media-player

  - title: Schlafzimmer
    path: schlafzimmer
    icon: mdi:hotel
    cards:
      - entities:
          - light.bett_gluhbirne
          - switch.regal_leds
          - switch.lichtschalter
          - light.leds_tisch
          - light.yeelight_strip1_34ce008b1863
          - switch.switch_bett
        show_header_toggle: true
        title: Licht & Strom
        type: entities
      - entities:
          - switch.fabian_strom
          - device_tracker.fabianpc
          - switch.fabian_pc_shutdown
          - sensor.fabian_strom_energy_today
          - sensor.fabian_strom_energy_power
        show_header_toggle: true
        title: Fabian PC
        type: entities
      - entity: climate.schlafzimmer
        type: thermostat
      - entity: media_player.schlafzimmer
        type: custom:mini-media-player

  - title: Gästezimmer
    icon: mdi:desktop-tower
    path: gastezimmer
    badges:
      - entity: sensor.gastezimmer_humidity
    cards:
      - entities:
          - light.lampe_gastezimmer
          - light.leds_gastezimmer
        show_header_toggle: true
        title: Licht
        type: entities
      - entities:
          - switch.nessie_pc
          - switch.nessie_pc_shutdown
          - device_tracker.nessiepc
        show_header_toggle: false
        title: Nessie PC
        type: entities
      - entity: climate.gastezimmer
        type: thermostat
      - entity: media_player.gastezimmer_mini
        type: custom:mini-media-player

  - title: Keller
    path: keller
    icon: mdi:washing-machine
    badges:
      - entity: sensor.washing_machine_state
      - entity: sensor.waschmaschine_energy_power
    cards:
      - entities:
          - switch.waschmaschine
          - input_boolean.kuehlschrank_keller
          - input_boolean.strom_keller
          - input_boolean.strom2_keller
        show_header_toggle: true
        title: Strom
        type: entities
      - entity: media_player.keller_tv
        type: custom:mini-media-player