---
- platform: dwd_illuminance
  entity_id: weather.dwd_weather_ebersberg_1h
## Waste sensors
- platform: waste_collection_schedule
  name: Restmüll
  details_format: upcoming
  count: 4
  value_template: "{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}"
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - "Restabfall"
    - "Restmüll"
- platform: waste_collection_schedule
  name: Altpapier
  details_format: upcoming
  count: 4
  value_template: "{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}"
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - "Altpapier"
    - "Papierabfall"
- platform: waste_collection_schedule
  name: Gelber_Sack
  details_format: upcoming
  count: 4
  value_template: "{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}"
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - "Gelber Sack"
- platform: waste_collection_schedule
  name: Bioabfall
  details_format: upcoming
  count: 4
  value_template: "{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}"
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - "BIO"
    - "Bioabfall"
#   - platform: spotcast
#     sp_dc: !secret sp_dc
#     sp_key: !secret sp_key
#   - platform: email
#     email: !secret vapid_email
#     password: !secret email_pw
#   - platform: feedparser
#     name: Corona News
#     feed_url: "https://www.rki.de/SiteGlobals/Functions/RSSFeed/RSSGenerator_nCoV.xml"
#     date_format: "%a, %d %b %H:%M:%S %Z"
#     inclusions:
#       - title
#       - description
#       - link
#       - pubDate
#     exclusions:
#       - language
#       - image
#   - platform: feedparser
#     name: Mydealz
#     feed_url: !secret mydealz_rss
#     date_format: "%a, %d %b %H:%M:%S %Z"
#     inclusions:
#       - title
#       - link
#       - pubDate
#     exclusions:
#       - language
#       - description
#       - image
- platform: tgtg
  email: "seitzf1@yahoo.de"
  access_token: "e30.eyJzdWIiOiIxNDczMTc3MCIsImV4cCI6MTY5NDA2NTc2NSwidCI6InJHT3I2SWlBVFd1SmliOHo0Skw5b3c6MDoxIn0.dNgOa_lZkG5Xq7zfimv-1GUg4sUTd-D2QRwUjiO5D5E"
  refresh_token: "e30.eyJzdWIiOiIxNDczMTc3MCIsImV4cCI6MTcyNTUxNTM2NSwidCI6IkFVblQyUGVDU0R5aG9PdmJaOUM2ZkE6MDowIn0.-FbqJ8vab5cS_3vrmYJi8u3jiNs3-oAl2h8riQCVQtM"
  user_id: "14731770"
  cookie: "datadome=7Shg~tlYK7Agp44ZGb6OFlr3ZTVwmkeD~GQnyOB9_PYKHUBuJj8tYrZ03MqxKLovNJLrYuKejIb2X0HezwkEuTJHO41Hq5sZp7L_WTSyiDu3cEStWbjKjgRhEo1KgY6K; Max-Age=5184000; Domain=.apptoogoodtogo.com; Path=/; Secure; SameSite=Lax"
  scan_interval: 900
