---
#   - platform: rest
#     name: Switch LAN-Play Online
#     resource: http://192.168.31.2:11451/info
#     scan_interval: 600
#     method: GET
#     unit_of_measurement: people
#     json_attributes:
#       - version
#       - idle
#     value_template: "{{value_json.online}}"
# - platform: imap_email_content
#   server: imap.ionos.de
#   port: 993
#   username: !secret juz_mail
#   password: !secret juz_mail_pw
#   senders:
#     - !secret vapid_email
#     - !secret juz_mail
#     - !secret gerhard_mail
#     - !secret fv_mail
#     - !secret moser_mail
#     - !secret grothe_mail
#     - !secret gl_mail
#     - !secret simon_mail
#     - !secret maxi_mail
#     - !secret fabi_yahoo_mail
#     - !secret gabi_mail
#     - !secret bm_mail
#     - !secret jugendpflege_mail
#     - !secret asenbeck_mail
#     - noreply@ionos.de
# - platform: imap
#   server: imap.ionos.de
#   username: !secret juz_mail
#   password: !secret juz_mail_pw
#   - platform: command_line
#     name: "Latest Tasmota"
#     command: l -s https://github.com/arendst/Tasmota/releases/latest | cut -d''"'' -f2 | rev | cut -d''/'' -f1 | cut -c 1- | cut -c -2 | rev'
#     scan_interval: 86400
- platform: template
  sensors:
    average_house_humidity:
      friendly_name: "Durchschn. Luftfeuchtigkeit"
      unique_id: "average_house_humidity_sensor"
      unit_of_measurement: "%"
      value_template: >-
        {% set humidity_values = [
            states.climate.samuel_s_zimmer.attributes.current_humidity | float(0),
            states.climate.wohnzimmer.attributes.current_humidity | float(0),
            states.climate.fabian_s_zimmer.attributes.current_humidity | float(0),
            states.climate.bad.attributes.current_humidity | float(0)
        ] %}
        {% set count = humidity_values | select('gt', 0) | list | length %}
        {% if count > 0 %}
          {{ (humidity_values | sum) / count | round(2) }}
        {% else %}
          0
        {% endif %}
      icon_template: "mdi:water-percent"

    average_house_temp:
      friendly_name: "Durchschn. Temp."
      unique_id: "average_house_temp"
      unit_of_measurement: "°C"
      value_template: >-
        {% set temp_values = [
            states.climate.samuel_s_zimmer.attributes.current_temperature | float(0),
            states.climate.wohnzimmer.attributes.current_temperature | float(0),
            states.climate.fabian_s_zimmer.attributes.current_temperature | float(0),
            states.climate.bad.attributes.current_temperature | float(0)
        ] %}
        {% set count = temp_values | select('gt', 0) | list | length %}
        {% if count > 0 %}
          {{ (temp_values | sum) / count | round(2) }}
        {% else %}
          0
        {% endif %}
      icon_template: "mdi:thermometer-auto"

    washing_machine_state:
      friendly_name: "Waschmaschine Status"
      unique_id: "washing_machine_state"
      value_template: "{{ states('input_select.washing_machine_status') }}"
      icon_template: "mdi:washing-machine"

    washing_machine_mode:
      friendly_name: "Waschmaschinen Modus"
      unique_id: "washing_machine_mode"
      value_template: >-
        {% if is_state("switch.waschmaschine", "on") %}
          {% if (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_30_degrees_pflegeleicht.attributes.last_triggered)) < 10000 %}
            30° Pflegeleicht
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_40_degrees_pflegeleicht.attributes.last_triggered)) < 10000 %}
            40° Pflegeleicht
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_20_degrees_feinwasche.attributes.last_triggered)) < 2800 %}
            20° Feinschwäsche
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_40_degrees_koch_bunt.attributes.last_triggered)) < 5500 %}
            40° Koch/Bunt
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_60_degrees_koch_bunt.attributes.last_triggered)) < 13000 %}
            60° Koch/Bunt
          {% else %}
            Unbekannt
          {% endif %}
        {% else %}
          Läuft nicht
        {% endif %}
      icon_template: "mdi:washing-machine"

    washing_machine_finish_time:
      friendly_name: "Waschmaschine Uhrzeit ca. fertig"
      unique_id: "washing_machine_finish_time"
      value_template: >-
        {% if is_state("switch.waschmaschine", "on") %}
          {% if (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_30_degrees_pflegeleicht.attributes.last_triggered)) < 9780 %}
            {{ (as_timestamp(states.automation.detect_if_washing_machine_is_currently_active.attributes.last_triggered) + 9780) | timestamp_custom("%H:%M", true) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_40_degrees_pflegeleicht.attributes.last_triggered)) < 9780 %}
            {{ (as_timestamp(states.automation.detect_if_washing_machine_is_currently_active.attributes.last_triggered) + 9780) | timestamp_custom("%H:%M", true) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_20_degrees_feinwasche.attributes.last_triggered)) < 2400 %}
            {{ (as_timestamp(states.automation.detect_if_washing_machine_is_currently_active.attributes.last_triggered) + 2400) | timestamp_custom("%H:%M", true) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_40_degrees_koch_bunt.attributes.last_triggered)) < 5220 %}
            {{ (as_timestamp(states.automation.detect_if_washing_machine_is_currently_active.attributes.last_triggered) + 5220) | timestamp_custom("%H:%M", true) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_60_degrees_koch_bunt.attributes.last_triggered)) < 12660 %}
            {{ (as_timestamp(states.automation.detect_if_washing_machine_is_currently_active.attributes.last_triggered) + 12660) | timestamp_custom("%H:%M", true) }}
          {% else %}
            {{ (as_timestamp(states.switch.waschmaschine.last_changed) + 9780) | timestamp_custom("%H:%M", true) }}
          {% endif %}
        {% else %}
          Läuft nicht
        {% endif %}
      icon_template: "mdi:home-clock"

    washing_machine_finish_duration:
      friendly_name: "Waschmaschine Dauer ca. fertig"
      unique_id: "washing_machine_finish_duration"
      value_template: >-
        {% if is_state("switch.waschmaschine", "on") %}
          {% if (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_30_degrees_pflegeleicht.attributes.last_triggered)) < 7200 %}
            {{ ((as_timestamp(states.switch.waschmaschine.last_changed) + 9780) - as_timestamp(now())) | timestamp_custom("%H:%M", false) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_40_degrees_pflegeleicht.attributes.last_triggered)) < 7200 %}
            {{ ((as_timestamp(states.switch.waschmaschine.last_changed) + 9780) - as_timestamp(now())) | timestamp_custom("%H:%M", false) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_20_degrees_feinwasche.attributes.last_triggered)) < 3200 %}
            {{ ((as_timestamp(states.switch.waschmaschine.last_changed) + 2400) - as_timestamp(now())) | timestamp_custom("%H:%M", false) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_40_degrees_koch_bunt.attributes.last_triggered)) < 7200 %}
            {{ ((as_timestamp(states.switch.waschmaschine.last_changed) + 5220) - as_timestamp(now())) | timestamp_custom("%H:%M", false) }}
          {% elif (as_timestamp(now()) - as_timestamp(states.automation.telegram_washing_mashine_set_program_60_degrees_koch_bunt.attributes.last_triggered)) < 14400 %}
            {{ ((as_timestamp(states.switch.waschmaschine.last_changed) + 13560) - as_timestamp(now())) | timestamp_custom("%H:%M", false) }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "min"
      icon_template: "mdi:home-clock"

    coal_lighter_finish_duration:
      friendly_name_template: >-
        {% if is_state("switch.kohleanzunder", "on") %}
          {% if as_timestamp(states.automation.detect_if_coal_lighter_is_currently_active.attributes.last_triggered) > as_timestamp(states.automation.detect_if_pizzamaker_is_currently_active.attributes.last_triggered) %}
            Kohle
          {% elif as_timestamp(states.automation.detect_if_pizzamaker_is_currently_active.attributes.last_triggered) > as_timestamp(states.automation.detect_if_coal_lighter_is_currently_active.attributes.last_triggered) %}
            Pizzamaker
          {% else %}
            Inaktiv
          {% endif %}
        {% else %}
          Inaktiv
        {% endif %}
      value_template: >-
        {% if is_state("switch.kohleanzunder", "on") %}
          {% if state_attr('sensor.coal_lighter_finish_duration', 'friendly_name') == 'Kohle' %}
            {{ ((as_timestamp(states.automation.detect_if_coal_lighter_is_currently_active.attributes.last_triggered) + 600) - as_timestamp(now())) | timestamp_custom("%M", false) }}
          {% elif state_attr('sensor.coal_lighter_finish_duration', 'friendly_name') == 'Pizzamaker' %}
            {{ ((as_timestamp(states.automation.detect_if_pizzamaker_is_currently_active.attributes.last_triggered) + 300) - as_timestamp(now())) | timestamp_custom("%M", false) }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      unique_id: "coal_lighter_finish_duration"
      unit_of_measurement: "min"
      icon_template: >-
        {% if is_state("switch.kohleanzunder", "on") %}
          {% if state_attr('sensor.coal_lighter_finish_duration', 'friendly_name') == 'Kohle' %}
            mdi:fire
          {% elif state_attr('sensor.coal_lighter_finish_duration', 'friendly_name') == 'Pizzamaker' %}
            mdi:pizza
          {% else %}
            mdi:fire-off
          {% endif %}
        {% else %}
          mdi:fire-off
        {% endif %}

    fs_caller:
      friendly_name: "Fabi Anrufer"
      unique_id: "fs_caller"
      value_template: "unbekannter"
      icon_template: "mdi:phone"
