- platform: google_maps
  username: !secret gmaps_mail
  max_gps_accuracy: 1000
  new_device_defaults:
    track_new_devices: false
- platform: google_maps
  username: !secret vapid_email
  max_gps_accuracy: 1000
  new_device_defaults:
    track_new_devices: true
